data = {

    'Custom': '自定义(cm)',
    'Final output x-axis pixels': '最终输出的x轴像素',
    'Final output y-axis pixels': '最终输出的y轴像素',
    'The number of pixels per inch': '每英寸包含的像素数量',
    'Paper width': '纸张宽度',
    'Paper height': '纸张高度',
    "Proportional scaling: Similar to enlarging images in Photoshop, the current XY is scaled proportionally up/down until one side matches the short side of the paper.": '等比自适应：类似ps放大图像,将当前XY等比例放大/缩小,直到一个边跟纸张的短边相同',
    'Enable or disable plugins': '启用或禁用插件',
    'Vertical': '纵',
    'Horizontal': '横',
    'Page Orientation': '方向',
    'Simple': '快速',
    'Accurate': '精确',
    "Output actual size image": '输出真实大小图片',
    "Output a small image, interpolate for enlargement": '输出一个小的图像,插值放大',
    'Vertical length': '竖向长',
    'Horizontal length': '横向长',
    "The required dependencies have been installed, please restart Blender": '所需依赖已安装,请重启blender',
    "Please install the dependencies required by the plugin first, restart Blender after installation is complete": '请先安装插件所需依赖,安装完成后重启blender',
    "Install the Pillow library": '安装pillow库',
    "Enable standard DPI output": '启用标准DPI输出',
    "Input:": '输入:',
    "Preset": '预设:',
    "Switch": '切换',
    "Width:": '横宽:',
    "Height:": '竖长:',
    "DPI:": 'DPI值:',
    "Pixels:": '像素:',
    "Scale:": '缩放:',
    "Output:": '输出:',
    "Proportional scaling": '等比自适应',
    "Force synchronization": '强制同步',
    "Please save the file first and set the output path": '请先保存文件,并设置输出路径',
    "The output path is in c:/tmp/": '输出路径在c:/tmp/',
    "The output path is in the current file directory": '输出路径在当前文件目录',
    "Please add an output node and set the output path": '请添加输出节点并设置输出路径',
    "Please set the output path": '请设置输出路径',
    "Please check the output node for the output location": '输出位置请查看合成输出节点',
    'AIGODLIKE Community:cupcko': '幻之境：cupcko',
    "Failed to save the image": '图片保存失败',
    "Set the image path first": '先设置图片路径',
    "Set the output node image path first": '先设置输出节点图片路径',
    "The output path format is unrecognizable, please check the output path": '输出路径格式无法识别,请检查输出路径',
}
